plumesim:
  frequency: 1
  color:
    r: 1.0
    g: 0.0
    b: 0.0
    a: 0.8
  type: meadering
  releasepoint:
    x: 0.1
    y: 1.5
    z: 0.0
  arena:
    start:
      x: 0.0
      y: 0.0
    end:
      x: 4.0
      y: 3.0
  number_of_points: 300
  release_rate: 10
  dispersion_coeficient: 0.006
  radius: 0.1
